name := "gatling-loki-logs"
version := "0.1.1"
scalaVersion := "2.13.12"

// Java 17 settings
javacOptions ++= Seq(
  "-source", "17",
  "-target", "17",
  "--release", "17"
)

// Scala compiler options for Java 17
scalacOptions ++= Seq(
  "-release", "17",
  "-deprecation",
  "-feature",
  "-unchecked"
)

// Publishing settings
organization := "io.perfana"
crossPaths := false // Disable Scala version in artifact name
publishMavenStyle := true

publishTo := Some(
  if (isSnapshot.value)
    Opts.resolver.sonatypeOssSnapshots.head
  else
    Opts.resolver.sonatypeStaging
)

// Source and Javadoc generation
Compile / packageDoc / publishArtifact := true
Compile / packageSrc / publishArtifact := true

// Javadoc settings
Compile / doc / scalacOptions ++= Seq(
  "-doc-title", "Gatling Loki Logs",
  "-doc-version", version.value,
  "-doc-footer", "Generated by sbt",
  "-doc-source-url", "https://github.com/example/repo/blob/main€{FILE_PATH}.scala"
)

// Configure HTTP client to follow redirects
updateOptions := updateOptions.value.withGigahorse(true)
// GPG signing settings
ThisBuild / pgpPassphrase := sys.env.get("PGP_PASSPHRASE").map(_.toCharArray)

// Sonatype repository publishing
//sonatypeCredentialHost := "s01.oss.sonatype.org"
// This becomes a simplified version of the above key.
publishTo := sonatypePublishToBundle.value
// Set this to the same value set as your credential files host.
sonatypeCredentialHost := "oss.sonatype.org"
// Set this to the repository to publish to using `s01.oss.sonatype.org`
// for accounts created after Feb. 2021.
sonatypeRepository := "https://oss.sonatype.org/service/local"
sonatypeProfileName := "io.perfana"
sonatypeCredentialHost := "oss.sonatype.org"

ThisBuild / pomIncludeRepository := { _ => false }

ThisBuild / publishTo := {
  // For accounts created after Feb 2021:
  // val nexus = "https://s01.oss.sonatype.org/"
  val nexus = "https://oss.sonatype.org/"
  if (isSnapshot.value) Some("snapshots" at nexus + "content/repositories/snapshots")
  else Some("releases" at nexus + "service/local/staging/deploy/maven2")
}
ThisBuild / publishMavenStyle := true


// SCM Information
scmInfo := Some(
  ScmInfo(
    url("https://github.com/perfana/gatling-loki-logs"),
    "scm:git:git://github.com/perfana/gatling-loki-logs.git"
  )
)

// Developer Information
developers := List(
  Developer(
    id    = "perfana",
    name  = "Daniel Moll",
    email = "daniel@perfana.io",
    url   = url("https://github.com/perfana")
  )
)

// Project Metadata
description := "Send Gatling's logs to Loki"
licenses := List("The MIT License (MIT)" -> url("https://opensource.org/licenses/MIT"))
homepage := Some(url("https://github.com/perfana/gatling-loki-logs"))

// Disable repository information in the POM
pomIncludeRepository := { _ => false }

// Local Publishing Configuration
publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
publishM2Configuration := publishM2Configuration.value.withOverwrite(true)

// Library dependencies
libraryDependencies ++= Seq(
  "ch.qos.logback" % "logback-classic" % "1.4.7" excludeAll ExclusionRule(organization = "org.slf4j"),
  "ch.qos.logback" % "logback-core" % "1.4.7",
  "com.github.loki4j" % "loki-logback-appender" % "1.5.0" excludeAll ExclusionRule(organization = "ch.qos.logback"),
  "net.logstash.logback" % "logstash-logback-encoder" % "7.4" excludeAll ExclusionRule(organization = "ch.qos.logback"),
  "org.slf4j" % "slf4j-api" % "2.0.7", // Explicit SLF4J 2.0.x
  "org.apache.httpcomponents.client5" % "httpclient5" % "5.2.1",
  "org.scalatest" %% "scalatest" % "3.2.15" % Test
)

// Dependency overrides
dependencyOverrides ++= Seq(
  "ch.qos.logback" % "logback-classic" % "1.4.7",
  "ch.qos.logback" % "logback-core" % "1.4.7",
  "org.slf4j" % "slf4j-api" % "2.0.7"
)