name: Release to Maven Central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SBT
        run: |
          echo "Installing SBT..."
          curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.zip
          unzip sbt.zip -d /usr/local
          export PATH=$PATH:/usr/local/sbt/bin

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Install dependencies
        run: sbt update

      - name: Run tests
        run: sbt test

      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |
          echo $PGP_SECRET | base64 --decode > /tmp/pgp-key.asc
          gpg --batch --import /tmp/pgp-key.asc
          sbt +publishSigned sonatypeBundleRelease